=== abdul-kader138/Algorith_Data_Structure_Learning/src/LearningBasic.xsd
<?xml version = "1.0"?>
<xsBabu:schema xmlns:xsBabu="http://www.w3.org/2001/XMLSchema"
               targetNamespace="http://www.javatpoint.com"
               xmlns="http://www.javatpoint.com"
               elementFormDefault="qualified">

    <xsBabu:element name="class">
        <xsBabu:complexType>
            <xsBabu:sequence>
                <xsBabu:element name="student" minOccurs="0" maxOccurs="unbounded"
                                type="studentType"/>
            </xsBabu:sequence>
        </xsBabu:complexType>
    </xsBabu:element>

    <xsBabu:complexType name="studentType">
        <xsBabu:sequence>
            <xsBabu:element name="name" type="xsBabu:string"></xsBabu:element>
            <xsBabu:element name="marks" type="xsBabu:integer"></xsBabu:element>
        </xsBabu:sequence>
        <xsBabu:attribute name="roll" type="xsBabu:positiveInteger"></xsBabu:attribute>
    </xsBabu:complexType>
</xsBabu:schema>

=== abdul-kader138/Algorith_Data_Structure_Learning/src/LearningBasicXsd.xml
<?xml version="1.0" ?>


<!--

   xmlns = define a source where XSD will
                     be available.

   -->

<class xmlns="http://www.javatpoint.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.javatpoint.com LearningBasic.xsd">
    <student roll="1">
        <name>Abdul Kader</name>
        <marks>89</marks>
    </student>


    <student roll="2">
        <name>Babu</name>
        <marks>90</marks>
    </student>

    <student roll="3">
        <name>Babu1</name>
        <marks>95</marks>
    </student>

</class>
