=== abdul-kader138/Algorith_Data_Structure_Learning/src/LearningBasic.dtd
<!ELEMENT employee (name? age,address)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT age (#PCDATA)>
        <!ELEMENT address (#PCDATA,house,road,city,country)>
        <!ELEMENT house (#PCDATA)>
        <!ELEMENT road (#PCDATA)>
        <!ELEMENT city (#PCDATA)>
        <!ELEMENT country (state,#PCDATA)>
        <!ELEMENT state (#PCDATA)>
        <!ATTLIST name id CDATA #REQUIRED>
        <!ATTLIST age id CDATA #IMPLIED>
        <!ATTLIST name s CDATA #REQUIRED>
        <!ENTITY test "Hello">

=== abdul-kader138/Algorith_Data_Structure_Learning/src/LearningBasic.xml
<?xml version="1.0"?>
<!DOCTYPE employee SYSTEM "LearningBasic.dtd" [
        <!ENTITY yest "&#97;">
        ]>
<employee>
    <name id="babu" s="5">Abdul kader</name>
    <age id="200">31</age>
    <address>
        <house>38</house>
        <road>11</road>
        <city>Dhaka</city>
        <country>
            <state>BD</state>
            Bangladesh
        </country>
        &yest;
    </address>

</employee>
